### ISSUE TITLE
[Epic] As a customer, I can purchase an item

### ISSUE THREAD

**Issue by nodox** [nodox/babylon#48]
We want to model how the user purchases an item on the frontend. 

AC: 
- [x] can see all the items on our site
- [x] can click on an item
- [x] can view an item
- [ ] can click buy button to view strip checkout modal
- [ ] can complete the stripe checkout form [TEST]
- [ ] can view a confirmation modal 
- [ ] can click view profile from the confirmation modal to go to their profile page and see their purchase history
- [ ] can click continue shopping on the confirmation modal to redirect back to the themes page

Could be an interesting task for @brimtown. Each task can be broken down into a couple PRs.
