### ISSUE TITLE
[Epic][Server] When a customer purchases an item...

### ISSUE THREAD

**Issue by nodox** [nodox/babylon#51]
We want to model what happens at the server level when a user

When a customer purchases an item, the server...

- [ ] receives a post request to an endpoint 
- [ ] the endpoint creates a new order
- [ ] the order is sent as a response
- [ ] the user can see the data from the order [WWW]
